WIDTH, HEIGHT = 700, 750
CELL_SIZE = 20
GRID_SIZE = WIDTH - CELL_SIZE * 2
ROWS_NUMBER, COLUMNS_NUMBER = GRID_SIZE // CELL_SIZE, GRID_SIZE // CELL_SIZE
MIN_INDEX = 0
MAX_INDEX = ROWS_NUMBER - 1
SUB_ORIGIN = 20
